Module api (#1)
* feat(module-api): server, db config setup

* feat(module-api): change jar to war packaging in pom.xml

* bug(module-api): fix 'NoClassDefFoundError: org/slf4j/impl/StaticLoggerBinder' with 'logback-classic' dependency

* bug(module-api): dependency conflict - remove unnecessary dependency

* feat(module-api): modify http response status, fix query mistake

* feat(module-api): filter various GET requests

* feat(module-api): user CRUD operations

* feat(module-api): user POST write comment

* feat(module-api): GET operations on user reviews